services:
  db:
    image: postgres:16
    container_name: booktracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server/BookTracker.Api
    container_name: booktracker_backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Email__SmtpHost: ${EMAIL_SMTP_HOST}
      Email__SmtpPort: ${EMAIL_SMTP_PORT}
      Email__Username: ${EMAIL_USERNAME}
      Email__Password: ${EMAIL_PASSWORD}
      Email__From: ${EMAIL_FROM}
      ClientBaseUrl: ${APP_CLIENT_BASE_URL}
    volumes:
      - ./server/BookTracker.Api/Images:/app/Images

  frontend:
    build:
      context: ./client
    container_name: booktracker_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

volumes:
  pgdata:
